#!/usr/bin/env python3
"""
GUILDS CLI - Command-line toolkit for GUILDS specifications

Commands:
  guilds new <name>                    Create a new .guilds spec from template
  guilds validate <spec>               Validate a spec without rendering
  guilds build <spec> [--backend]      Build GUI for specified backend
  guilds render <spec> <phase> [--backend]  Render static output for a phase
  guilds compile <spec> [--backend]    Compile to standalone executable
  guilds serve <spec>                  Start dev server with hot reload
  guilds serve --builder               Start the visual builder server
  guilds export <spec> <fmt>           Export to JSON, React, Vue, events, or state machines
  guilds pdf <input>                   Generate a formatted PDF from a local file

Backends:
  html       - Web-based HTML/CSS/JS SPA (default)
  python-tk  - Python tkinter desktop application
  python-qt  - Python PyQt5 desktop application (alias for pyqt5)
  pyqt5      - Python PyQt5 desktop application
  pyqt6      - Python PyQt6 desktop application
  pyside6    - Python PySide6 desktop application (recommended for compile)
  cpp-qt     - C++ Qt application
  cpp-imgui  - C++ Dear ImGui application
"""

import argparse
import http.server
import json
import os
import socketserver
import subprocess
import sys
import threading
import time
from pathlib import Path

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
    HAS_WATCHDOG = True
except ImportError:
    HAS_WATCHDOG = False

# Ensure we can import the relocated GUILDS modules and renderer package.
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

try:
    from guilds_parser import parse_source, LexError, ParseError
    from guilds_evaluator import (
        Evaluator,
        EvalContext,
        ALL_PHASES,
        PHASE_NAMES,
        PHASE_ORIENT,
        PHASE_EXECUTE,
        PHASE_VERIFY,
        PHASE_INTEGRATE,
        PHASE_RECOVER,
        PHASE_IDLE,
    )
    from guilds_live_builder import build_bundle, build_html
except ImportError as e:
    print(f"Error importing GUILDS modules: {e}")
    print("Make sure the core modules are available under core/ and the renderer package is available under guilds_renderers/.")
    sys.exit(1)

# Available backends
AVAILABLE_BACKENDS = [
    'html',        # Self-contained HTML/CSS/JS SPA
    'python-tk',   # Python tkinter desktop app
    'python-qt',   # Python PyQt5 desktop app (alias for pyqt5)
    'pyqt5',       # Python PyQt5 desktop app
    'pyqt6',       # Python PyQt6 desktop app
    'pyside6',     # Python PySide6 desktop app
    'cpp-qt',      # C++ Qt application
    'cpp-imgui',   # C++ Dear ImGui application
]

PHASE_NAME_TO_CONST = {
    "orient": PHASE_ORIENT,
    "execute": PHASE_EXECUTE,
    "verify": PHASE_VERIFY,
    "integrate": PHASE_INTEGRATE,
    "recover": PHASE_RECOVER,
    "idle": PHASE_IDLE,
}


def _phase_to_const(phase_name: str, default: str = "execute") -> str:
    """Map human phase names to evaluator constants."""
    return PHASE_NAME_TO_CONST.get(phase_name, PHASE_NAME_TO_CONST[default])


def _collect_declarations(program):
    """Normalize AST declarations into typed lists."""
    buckets = {
        "claims": [],
        "affords": [],
        "vessels": [],
        "stages": [],
        "flows": [],
        "bonds": [],
        "seams": [],
    }

    for decl in getattr(program, "declarations", []):
        kind = decl.__class__.__name__
        if kind == "ClaimDecl":
            buckets["claims"].append(decl)
        elif kind == "AffordDecl":
            buckets["affords"].append(decl)
        elif kind == "VesselDecl":
            buckets["vessels"].append(decl)
        elif kind == "StageDecl":
            buckets["stages"].append(decl)
        elif kind == "FlowDecl":
            buckets["flows"].append(decl)
        elif kind == "BondDecl":
            buckets["bonds"].append(decl)
        elif kind == "SeamDecl":
            buckets["seams"].append(decl)

    return buckets


def _format_certainty(certainty):
    if not certainty:
        return "unknown"
    return getattr(certainty, "kind", str(certainty))


def _format_stakes(stakes):
    if not stakes:
        return "medium"
    return getattr(stakes, "level", str(stakes))


def _copy_text_file(src: Path, dest: Path):
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(src.read_text(encoding='utf-8'), encoding='utf-8')


def _find_builder_static_root():
    dist_dir = REPO_ROOT / "builder" / "dist"
    if dist_dir.exists():
        return dist_dir
    return REPO_ROOT / "docs"


# =============================================================================
# TEMPLATES
# =============================================================================

BASIC_TEMPLATE = '''\
-- {name} GUILDS Specification
-- Generated by guilds new

-- Certainty bindings
let knownCert = certain
let inferredCert = inferred

-- Main content claim
claim MainContent {{
    content:     text(content_data)
    certainty:   inferred
    provenance:  source.direct(system)
    stakes:      medium
    freshness:   live
    on_stale:    mark_stale
}}

-- Primary action
afford PrimaryAction {{
    perceivable:  always_visible
    offered:      activate
    requires:     [action_ready]
    contracts: [
        contract ActionContract {{
            trigger:     user_action(PrimaryAction)
            obligation:  execute(do_action)
            deadline:    ms(200)
            on_breach:   degraded
        }}
    ]
    on_unavail:   fade_locked
}}

-- Main vessel
vessel MainVessel {{
    budget:      whole(1.0)
    phase:       any
    weight:      primary
    arrangement: sequence(primary, [1.0])
    contains:    [MainContent, PrimaryAction]
}}

-- Phase-coupled stage
stage {name}Stage {{
    budget:  whole(1.0)

    phases: {{
        idle: {{
            arrangement: sequence(primary, [1.0])
            visible:     [MainVessel]
            faded:       []
            hidden:      []
            dominant:    MainVessel
        }}
        execute: {{
            arrangement: sequence(primary, [1.0])
            visible:     [MainVessel]
            faded:       []
            hidden:      []
            dominant:    MainVessel
        }}
    }}

    default: {{
        arrangement: sequence(primary, [1.0])
        visible:     [MainVessel]
        faded:       []
        hidden:      []
        dominant:    MainVessel
    }}

    transition: {{
        duration:   ms(150)
        curve:      ease-out
        sequence:   anchor_first
    }}
}}
'''


# =============================================================================
# COMMANDS
# =============================================================================

def cmd_new(args):
    """Create a new GUILDS specification from template."""
    name = args.name
    filename = f"{name.lower()}.guilds"

    if os.path.exists(filename) and not args.force:
        print(f"Error: {filename} already exists. Use --force to overwrite.")
        return 1

    content = BASIC_TEMPLATE.format(name=name.title())

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Created {filename}")
    print(f"\nNext steps:")
    print(f"  1. Edit {filename} to define your UI")
    print(f"  2. Validate: guilds validate {filename}")
    print(f"  3. Build:    guilds build {filename}")
    return 0


def cmd_validate(args):
    """Validate a GUILDS specification."""
    spec_path = args.spec

    if not os.path.exists(spec_path):
        print(f"Error: {spec_path} not found")
        return 1

    with open(spec_path, 'r', encoding='utf-8') as f:
        src = f.read()

    source_name = os.path.splitext(os.path.basename(spec_path))[0]

    try:
        program, violations = parse_source(src, source_name)
    except (LexError, ParseError) as e:
        print(f"FATAL: {e}")
        return 2

    errors = [v for v in violations if v.severity == "error"]
    warnings = [v for v in violations if v.severity == "warning"]

    if errors:
        print(f"\n{len(errors)} error(s):")
        for v in errors:
            print(f"  [{v.code}] {v.message}")

    if warnings:
        print(f"\n{len(warnings)} warning(s):")
        for v in warnings:
            print(f"  [{v.code}] {v.message}")

    if not errors and not warnings:
        decls = _collect_declarations(program)
        print(f"✓ {spec_path} is valid")

        # Show summary
        print(f"\nSummary:")
        print(f"  Claims:     {len(decls['claims'])}")
        print(f"  Affordances:{len(decls['affords'])}")
        print(f"  Vessels:    {len(decls['vessels'])}")
        print(f"  Stages:     {len(decls['stages'])}")
        print(f"  Flows:      {len(decls['flows'])}")
        print(f"  Bonds:      {len(decls['bonds'])}")
        print(f"  Seams:      {len(decls['seams'])}")

    return 1 if errors else 0


def cmd_build(args):
    """Build GUI from specification for the specified backend."""
    spec_path = args.spec
    backend = getattr(args, 'backend', 'html') or 'html'

    if not os.path.exists(spec_path):
        print(f"Error: {spec_path} not found")
        return 1

    # For HTML backend, use the existing live builder
    if backend == 'html':
        with open(spec_path, 'r', encoding='utf-8') as f:
            src = f.read()

        source_name = os.path.splitext(os.path.basename(spec_path))[0]
        out_path = args.output
        if out_path is None:
            out_dir = Path("outputs") / source_name
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = str(out_dir / "guilds_live.html")
        else:
            out_path = str(Path(out_path))
            Path(out_path).parent.mkdir(parents=True, exist_ok=True)

        print(f"Compiling {source_name}...", file=sys.stderr)
        bundle = build_bundle(src, source_name)
        print(f"  {len(bundle['phases'])} phases evaluated", file=sys.stderr)
        print(f"  {len(bundle['transitions'])} transition plans", file=sys.stderr)
        print(f"  {len(bundle['cascadeIndex'])} cascade paths pre-computed", file=sys.stderr)

        html = build_html(bundle, source_name)
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(html)

        size_kb = os.path.getsize(out_path) / 1024
        print(f"  Written: {out_path}  ({size_kb:.0f} KB)", file=sys.stderr)
        return 0

    # For other backends, use the new renderer system
    return build_with_backend(spec_path, backend, args.output)


def cmd_render(args):
    """Render static output for a specific phase."""
    spec_path = args.spec
    phase = args.phase
    backend = getattr(args, 'backend', 'html') or 'html'

    if not os.path.exists(spec_path):
        print(f"Error: {spec_path} not found")
        return 1

    # For HTML backend, use the existing renderer
    if backend == 'html':
        from guilds_renderer import RenderTreeBuilder, HTMLRenderer

        with open(spec_path, 'r', encoding='utf-8') as f:
            src = f.read()

        source_name = os.path.splitext(os.path.basename(spec_path))[0]
        try:
            program, _violations = parse_source(src, source_name)
        except (LexError, ParseError) as e:
            print(f"FATAL: {e}")
            return 2

        ctx = EvalContext(phase=_phase_to_const(phase, default="execute"), now=time.time())
        ev = Evaluator(program, ctx)
        model = ev.evaluate()

        builder = RenderTreeBuilder(model, ev)
        tree = builder.build()

        renderer = HTMLRenderer()
        html = renderer.render(tree, title=f"GUILDS · {source_name}")
        out_dir = Path("outputs") / source_name
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"guilds_surface_{phase}.html"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"HTML written: {out_path}")
        return 0

    # For other backends, use the new renderer system with phase
    return build_with_backend(spec_path, backend, None, phase)


def build_with_backend(spec_path: str, backend: str, output: str = None, phase: str = "execute"):
    """Build GUI using the specified backend renderer."""
    from guilds_renderer import RenderTreeBuilder

    # Parse and evaluate
    with open(spec_path, 'r', encoding='utf-8') as f:
        src = f.read()

    source_name = os.path.splitext(os.path.basename(spec_path))[0]

    try:
        program, violations = parse_source(src, source_name)
    except (LexError, ParseError) as e:
        print(f"FATAL: {e}")
        return 2

    phase_const = _phase_to_const(phase, default="execute")

    ctx = EvalContext(phase=phase_const, now=time.time())
    ev = Evaluator(program, ctx)
    model = ev.evaluate()

    # Build render tree
    builder = RenderTreeBuilder(model, ev)
    tree = builder.build()

    # Convert tree to the format expected by the new renderers
    from guilds_renderers.base import RenderTree as NewRenderTree, RenderNode as NewRenderNode, RenderStyle

    def convert_node(old_node):
        """Convert old RenderNode to new RenderNode format."""
        return NewRenderNode(
            name=old_node.name,
            kind=old_node.kind.name.lower(),
            visibility=old_node.visibility,
            style=RenderStyle(
                opacity=old_node.style.opacity,
                flex_grow=old_node.style.flex_grow,
                font_weight=old_node.style.font_weight,
                font_size_em=old_node.style.font_size_em,
                border_px=old_node.style.border_px,
                border_colour=old_node.style.border_colour,
                bg_colour=old_node.style.bg_colour,
                fg_colour=old_node.style.fg_colour,
                accent_colour=old_node.style.accent_colour,
                is_dominant=old_node.style.is_dominant,
                is_anchor=old_node.style.is_anchor,
                is_stalled=old_node.style.is_stalled,
                has_failure=old_node.style.has_failure,
                failure_colour=old_node.style.failure_colour,
                axis=old_node.style.axis,
                gap_em=old_node.style.gap_em,
            ),
            label=old_node.label,
            subtitle=old_node.subtitle,
            certainty=old_node.certainty,
            flow_state=old_node.flow_state,
            active_failure=old_node.active_failure,
            children=[convert_node(c) for c in old_node.children],
            meta=old_node.meta,
            arrangement_kind=old_node.arrangement_kind,
        )

    new_tree = NewRenderTree(
        roots=[convert_node(r) for r in tree.roots],
        phase=tree.phase,
        phase_name=tree.phase_name,
        phase_colour=tree.phase_colour,
        lambda_omega=tree.lambda_omega,
        budget_warnings=tree.budget_warnings,
        symbol_errors=tree.symbol_errors,
        active_failures=tree.active_failures,
    )

    # Attach per-phase top-level visibility maps for desktop backends.
    # All phase sigil words used as canonical keys.
    known_phases = {"idle", "orient", "execute", "verify", "integrate", "recover"}
    phase_visibility = {}
    phase_dominant = {}
    for stage in ev.sym.stages.values():
        configs = dict(stage.phases)
        if stage.default:
            for phase_key in known_phases:
                configs.setdefault(phase_key, stage.default)
        for phase_key, cfg in configs.items():
            phase_label = phase_key
            states = phase_visibility.setdefault(phase_label, {})
            def record(name: str, state: str):
                if name in ev.sym.vessels:
                    states[f"vessel_{name}"] = state
                elif name in ev.sym.claims:
                    states[f"claim_{name}"] = state
                elif name in ev.sym.affords:
                    states[f"afford_{name}"] = state
            for name in cfg.visible:
                record(name, "render")
            for name in cfg.faded:
                record(name, "fade")
            for name in cfg.hidden:
                record(name, "hide")
            if cfg.dominant:
                phase_dominant[phase_label] = f"vessel_{cfg.dominant}"

    new_tree.phase_visibility = phase_visibility
    new_tree.phase_dominant = phase_dominant

    # Get the renderer
    try:
        from guilds_renderers import get_renderer
        renderer = get_renderer(backend)
    except (ImportError, ValueError) as e:
        print(f"Error loading backend '{backend}': {e}")
        return 1

    # Render
    app_name = source_name.title().replace('_', '').replace('-', '')

    # Set up output directory
    out_dir = Path(output) if output else Path("outputs") / source_name
    out_dir.mkdir(parents=True, exist_ok=True)

    # Handle multi-file outputs (C++ backends)
    if hasattr(renderer, 'render_files'):
        files = renderer.render_files(new_tree, app_name)
        for filename, content in files.items():
            out_path = out_dir / filename
            with open(out_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Generated: {out_path}")
    else:
        # Single file output
        result = renderer.render(new_tree, app_name=app_name)
        output_files = renderer.output_files(source_name)
        out_path = out_dir / output_files[0]
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(result)
        print(f"Generated: {out_path}")

    print(f"\nBackend: {backend}")
    print(f"Output directory: {out_dir}")

    # Print backend-specific instructions
    if backend == 'python-tk':
        print(f"\nTo run: python {out_dir / 'guilds_app_tk.py'}")
    elif backend == 'python-qt':
        print(f"\nTo run: python {out_dir / 'guilds_app_pyqt5.py'}")
        print("(Requires: pip install PyQt5)")
    elif backend == 'cpp-qt':
        print(f"\nTo build:")
        print(f"  cd {out_dir}")
        print(f"  mkdir build && cd build")
        print(f"  cmake .. && make")
        print(f"  ./{app_name}")
    elif backend == 'cpp-imgui':
        print(f"\nTo use: Include guilds_ui.h in your ImGui project")
        print(f"  1. Add guilds_ui.h and guilds_ui.cpp to your project")
        print(f"  2. Create Guilds::GuildsUI instance")
        print(f"  3. Call render() in your ImGui loop")

    return 0


def cmd_serve(args):
    """Start development server with hot reload."""
    if getattr(args, 'builder', False):
        port = args.port
        serve_root = _find_builder_static_root()
        index_name = "index.html" if serve_root.name == "dist" else "react_gui_builder.html"

        if not serve_root.exists():
            print("Error: Builder assets not found.")
            print("Expected either builder/dist/ or docs/react_gui_builder.html.")
            return 1

        original_dir = os.getcwd()
        os.chdir(serve_root)

        class BuilderHandler(http.server.SimpleHTTPRequestHandler):
            def do_GET(self):
                if self.path in ('/', ''):
                    self.path = '/' + index_name
                return super().do_GET()

        with socketserver.TCPServer(("", port), BuilderHandler) as httpd:
            print(f"\nServing visual builder at http://localhost:{port}")
            if serve_root.name != "dist":
                print("Using fallback static builder page from docs/.")
                print("For the full Vite app, run: cd builder && npm install && npm run dev")
            print("Press Ctrl+C to stop\n")
            try:
                httpd.serve_forever()
            except KeyboardInterrupt:
                print("\nStopping...")

        os.chdir(original_dir)
        return 0

    spec_path = args.spec
    port = args.port

    if not spec_path:
        print("Error: spec is required unless you use --builder")
        return 1

    if not os.path.exists(spec_path):
        print(f"Error: {spec_path} not found")
        return 1

    source_name = os.path.splitext(os.path.basename(spec_path))[0]
    out_dir = Path("outputs") / source_name
    out_file = out_dir / "guilds_live.html"

    # Initial build
    print(f"Building {spec_path}...")
    cmd_build(argparse.Namespace(spec=spec_path, output=None, backend='html'))

    observer = None

    if HAS_WATCHDOG:
        # File watcher for hot reload
        class RebuildHandler(FileSystemEventHandler):
            def __init__(self):
                self.last_build = 0

            def on_modified(self, event):
                if event.src_path.endswith('.guilds'):
                    # Debounce
                    now = time.time()
                    if now - self.last_build < 1:
                        return
                    self.last_build = now

                    print(f"\n{event.src_path} changed, rebuilding...")
                    cmd_build(argparse.Namespace(spec=spec_path, output=None, backend='html'))

        observer = Observer()
        observer.schedule(RebuildHandler(), path='.', recursive=False)
        observer.start()
    else:
        print("Note: Install watchdog for hot reload (pip install watchdog)")

    # Start HTTP server
    original_dir = os.getcwd()
    os.chdir(out_dir)

    handler = http.server.SimpleHTTPRequestHandler

    with socketserver.TCPServer(("", port), handler) as httpd:
        print(f"\nServing at http://localhost:{port}")
        if HAS_WATCHDOG:
            print(f"Watching {spec_path} for changes...")
        print("Press Ctrl+C to stop\n")

        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopping...")
            if observer:
                observer.stop()

    if observer:
        observer.join()

    os.chdir(original_dir)
    return 0


def cmd_export(args):
    """Export specification to different formats."""
    spec_path = args.spec
    fmt = args.format

    if not os.path.exists(spec_path):
        print(f"Error: {spec_path} not found")
        return 1

    with open(spec_path, 'r', encoding='utf-8') as f:
        src = f.read()

    source_name = os.path.splitext(os.path.basename(spec_path))[0]

    try:
        program, violations = parse_source(src, source_name)
    except (LexError, ParseError) as e:
        print(f"FATAL: {e}")
        return 2

    out_dir = Path("outputs") / source_name
    out_dir.mkdir(parents=True, exist_ok=True)

    if fmt == "json":
        # Export as JSON bundle
        with open(spec_path, 'r', encoding='utf-8') as f:
            src = f.read()
        bundle = build_bundle(src, source_name)

        out_file = out_dir / f"{source_name}.json"
        with open(out_file, 'w', encoding='utf-8') as f:
            json.dump(bundle, f, indent=2)

        print(f"Exported JSON: {out_file}")

    elif fmt == "react":
        # Export as React component
        export_react(program, source_name, out_dir)

    elif fmt == "vue":
        # Export as Vue component
        export_vue(program, source_name, out_dir)

    elif fmt == "events":
        # Export event schema for integration
        export_event_schema(program, source_name, out_dir)

    elif fmt == "statemachine":
        export_state_machine(program, source_name, out_dir)

    else:
        print(f"Unknown format: {fmt}")
        print("Supported: json, react, vue, events, statemachine")
        return 1

    return 0


def export_react(program, name, out_dir):
    """Generate React component from GUILDS spec."""

    # Generate component for each vessel
    components = []
    decls = _collect_declarations(program)

    for vessel in decls["vessels"]:
        component = f'''
import React from 'react';

export function {vessel.name}({{ phase, onAction }}) {{
  return (
    <div className="guilds-vessel guilds-{vessel.name.lower()}" data-phase={{phase}}>
      {{/* Contains: {', '.join(c if isinstance(c, str) else c.name for c in vessel.contains)} */}}
      <div className="guilds-content">
        {{/* Render children based on phase */}}
      </div>
    </div>
  );
}}
'''
        components.append((vessel.name, component))

    # Main component
    main = f'''
import React, {{ useState, useEffect }} from 'react';
{chr(10).join(f"import {{ {name} }} from './{name}';" for name, _ in components)}

const PHASES = ['idle', 'orient', 'execute', 'verify', 'integrate', 'recover'];

export function {name.title()}GUI({{ initialPhase = 'idle', onPhaseChange, onEvent }}) {{
  const [phase, setPhase] = useState(initialPhase);

  const handlePhaseChange = (newPhase) => {{
    setPhase(newPhase);
    onPhaseChange?.(newPhase);
  }};

  const handleAction = (action, data) => {{
    onEvent?.({{ type: action, data, phase }});
  }};

  return (
    <div className="guilds-app" data-phase={{phase}}>
      <div className="guilds-phase-selector">
        {{PHASES.map(p => (
          <button
            key={{p}}
            onClick={{() => handlePhaseChange(p)}}
            className={{phase === p ? 'active' : ''}}
          >
            {{p}}
          </button>
        ))}}
      </div>
      <div className="guilds-content">
        {{/* Render stage content */}}
      </div>
    </div>
  );
}}

export default {name.title()}GUI;
'''

    # Write files
    for comp_name, comp_code in components:
        with open(out_dir / f"{comp_name}.jsx", 'w', encoding='utf-8') as f:
            f.write(comp_code)

    with open(out_dir / f"{name.title()}GUI.jsx", 'w', encoding='utf-8') as f:
        f.write(main)

    # CSS
    css = '''
.guilds-app {
  font-family: system-ui, sans-serif;
}

.guilds-vessel {
  padding: 1rem;
  border-radius: 8px;
}

.guilds-phase-selector button.active {
  background: #3b82f6;
  color: white;
}

[data-phase="idle"] { --phase-color: #6b7280; }
[data-phase="orient"] { --phase-color: #8b5cf6; }
[data-phase="execute"] { --phase-color: #3b82f6; }
[data-phase="verify"] { --phase-color: #22c55e; }
[data-phase="integrate"] { --phase-color: #14b8a6; }
[data-phase="recover"] { --phase-color: #f59e0b; }
'''

    with open(out_dir / "guilds.css", 'w', encoding='utf-8') as f:
        f.write(css)

    print(f"Exported React components to {out_dir}/")
    print(f"  - {name.title()}GUI.jsx (main component)")
    print(f"  - {len(components)} vessel components")
    print(f"  - guilds.css")


def export_vue(program, name, out_dir):
    """Generate Vue component from GUILDS spec."""

    vue = f'''
<template>
  <div class="guilds-app" :data-phase="phase">
    <div class="guilds-phase-selector">
      <button
        v-for="p in phases"
        :key="p"
        @click="setPhase(p)"
        :class="{{ active: phase === p }}"
      >
        {{{{ p }}}}
      </button>
    </div>
    <div class="guilds-content">
      <!-- Render stage content -->
    </div>
  </div>
</template>

<script>
export default {{
  name: '{name.title()}GUI',

  props: {{
    initialPhase: {{
      type: String,
      default: 'idle'
    }}
  }},

  data() {{
    return {{
      phase: this.initialPhase,
      phases: ['idle', 'orient', 'execute', 'verify', 'integrate', 'recover']
    }};
  }},

  methods: {{
    setPhase(newPhase) {{
      this.phase = newPhase;
      this.$emit('phase-change', newPhase);
    }},

    handleAction(action, data) {{
      this.$emit('action', {{ type: action, data, phase: this.phase }});
    }}
  }}
}};
</script>

<style scoped>
.guilds-app {{
  font-family: system-ui, sans-serif;
}}

.guilds-phase-selector button.active {{
  background: #3b82f6;
  color: white;
}}
</style>
'''

    with open(out_dir / f"{name.title()}GUI.vue", 'w', encoding='utf-8') as f:
        f.write(vue)

    print(f"Exported Vue component: {out_dir}/{name.title()}GUI.vue")


def export_event_schema(program, name, out_dir):
    """Export event schema for integration with other programs."""
    decls = _collect_declarations(program)

    events = {
        "name": name,
        "version": "1.0",
        "phases": ["idle", "orient", "execute", "verify", "integrate", "recover"],
        "events": {
            "incoming": [],
            "outgoing": []
        },
        "actions": [],
        "claims": []
    }

    # Extract affordances as actions
    for afford in decls["affords"]:
        action = {
            "name": afford.name,
            "trigger": "user_action",
            "contracts": len(afford.contracts) if afford.contracts else 0
        }
        events["actions"].append(action)
        events["events"]["outgoing"].append({
            "type": f"action:{afford.name}",
            "payload": {"action": afford.name}
        })

    # Extract claims
    for claim in decls["claims"]:
        c = {
            "name": claim.name,
            "certainty": _format_certainty(claim.certainty),
            "stakes": _format_stakes(claim.stakes)
        }
        events["claims"].append(c)

    # Common incoming events
    events["events"]["incoming"] = [
        {"type": "phase:change", "payload": {"phase": "string"}},
        {"type": "data:update", "payload": {"claim": "string", "value": "any"}},
        {"type": "failure:inject", "payload": {"kind": "string", "vessel": "string"}}
    ]

    out_file = out_dir / f"{name}_events.json"
    with open(out_file, 'w', encoding='utf-8') as f:
        json.dump(events, f, indent=2)

    print(f"Exported event schema: {out_file}")
    print(f"\nIntegration example:")
    print(f'''
  // In your application:
  const guildsFrame = document.getElementById('guilds-frame');

  // Send events to GUILDS UI
  guildsFrame.contentWindow.postMessage({{
    type: 'phase:change',
    payload: {{ phase: 'execute' }}
  }}, '*');

  // Receive events from GUILDS UI
  window.addEventListener('message', (event) => {{
    if (event.data.type?.startsWith('action:')) {{
      console.log('User action:', event.data);
    }}
  }});
''')


def export_state_machine(program, name, out_dir):
    """Export flows as state-machine artifacts."""
    decls = _collect_declarations(program)
    flows = decls["flows"]

    def mermaid_id(value):
        cleaned = "".join(ch if ch.isalnum() else "_" for ch in str(value))
        cleaned = cleaned.strip("_")
        return cleaned or "state"

    machines = []
    for flow in flows:
        states = []
        transitions = []

        for index, step in enumerate(flow.steps):
            state = {
                "id": step.name,
                "kind": step.state,
                "duration": getattr(step.duration, "kind", str(step.duration)),
                "claim": getattr(step.claim, "name", None) if hasattr(step.claim, "name") else (step.claim if isinstance(step.claim, str) else None),
                "affordances": list(step.affordances),
                "exit_condition": step.exit_cond,
            }
            states.append(state)

            if index + 1 < len(flow.steps):
                transitions.append({
                    "from": step.name,
                    "to": flow.steps[index + 1].name,
                    "trigger": step.exit_cond or "next",
                })

        if flow.terminal and flow.steps:
            for terminal in flow.terminal:
                transitions.append({
                    "from": flow.steps[-1].name,
                    "to": terminal,
                    "trigger": "terminal",
                })

        machines.append({
            "name": flow.name,
            "trigger": getattr(flow.trigger, "kind", str(flow.trigger)),
            "states": states,
            "transitions": transitions,
            "stall": {
                "threshold": getattr(getattr(flow.on_stall, "threshold", None), "kind", None),
                "recovery": list(getattr(flow.on_stall, "recovery", []) or []),
            } if flow.on_stall else None,
        })

    payload = {
        "name": name,
        "version": "1.0",
        "machines": machines,
    }

    json_file = out_dir / f"{name}_statemachine.json"
    with open(json_file, 'w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2)

    mermaid_lines = ["stateDiagram-v2"]
    if not machines:
        mermaid_lines.append("    [*] --> NoFlowsDeclared")
    else:
        for machine in machines:
            mermaid_lines.append(f"    state {mermaid_id(machine['name'])} {{")
            if machine["states"]:
                mermaid_lines.append(f"        [*] --> {mermaid_id(machine['states'][0]['id'])}")
            for transition in machine["transitions"]:
                mermaid_lines.append(
                    f"        {mermaid_id(transition['from'])} --> {mermaid_id(transition['to'])}: {transition['trigger']}"
                )
            mermaid_lines.append("    }")

    mermaid_file = out_dir / f"{name}_statemachine.mmd"
    with open(mermaid_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(mermaid_lines) + "\n")

    print(f"Exported state machine JSON: {json_file}")
    print(f"Exported state machine Mermaid: {mermaid_file}")
    print(f"  Flows exported: {len(machines)}")


# =============================================================================
# COMPILE COMMAND
# =============================================================================

# Backends that support compilation to executable
COMPILABLE_BACKENDS = ['python-tk', 'pyqt5', 'pyqt6', 'pyside6', 'python-qt']


def cmd_compile(args):
    """Compile a GUILDS spec to a standalone executable."""
    spec_path = Path(args.spec)
    if not spec_path.exists():
        print(f"Error: File not found: {spec_path}")
        return 1

    # Check if PyInstaller is available
    try:
        import PyInstaller.__main__
    except ImportError:
        print("Error: PyInstaller is not installed.")
        print("Install it with: pip install pyinstaller")
        return 1

    backend = args.backend

    # Validate backend supports compilation
    if backend not in COMPILABLE_BACKENDS:
        print(f"Error: Backend '{backend}' does not support compilation to executable.")
        print(f"Supported backends: {', '.join(COMPILABLE_BACKENDS)}")
        return 1

    name = spec_path.stem
    out_dir = Path(args.output) if args.output else Path('outputs') / name

    print(f"Compiling {spec_path} with backend '{backend}'...")

    # Step 1: Generate Python source
    try:
        source = spec_path.read_text(encoding='utf-8')
        program, violations = parse_source(source, name)
    except (LexError, ParseError) as e:
        print(f"Parse error: {e}")
        return 1

    # Check for errors
    errors = [v for v in violations if v.severity == "error"]
    if errors:
        print(f"Specification has {len(errors)} error(s):")
        for e in errors[:5]:
            print(f"  - {e}")
        return 1

    # Evaluate using evaluator phase constants (string names bypass stage phase configs).
    ctx = EvalContext(phase=_phase_to_const("idle", default="idle"), now=time.time())
    evaluator = Evaluator(program, ctx)
    surface = evaluator.evaluate()

    # Build with the specified backend
    from guilds_renderers import get_renderer
    from guilds_renderer import RenderTreeBuilder

    builder = RenderTreeBuilder(surface, evaluator)
    tree = builder.build()

    renderer = get_renderer(backend)

    # Convert tree if needed (renderer may expect different format)
    from guilds_renderers.base import RenderTree as NewRenderTree, RenderNode as NewRenderNode, RenderStyle

    def convert_node(old_node):
        style = RenderStyle(
            is_dominant=getattr(old_node.style, 'is_dominant', False) if hasattr(old_node, 'style') else False,
            opacity=0.6 if old_node.visibility == "fade" else 1.0,
        )
        # Convert kind to string if it's an enum
        kind = old_node.kind
        if hasattr(kind, 'name'):
            # Enum - use the name
            kind = kind.name.lower()
        elif isinstance(kind, str):
            kind = kind.lower()
        else:
            kind = str(kind).lower()

        new_node = NewRenderNode(
            name=old_node.name,
            kind=kind,
            visibility=old_node.visibility,
            style=style,
            label=old_node.label,
            subtitle=getattr(old_node, 'subtitle', None),
            certainty=getattr(old_node, 'certainty', None),
            flow_state=getattr(old_node, 'flow_state', None),
            active_failure=getattr(old_node, 'failure', None) or getattr(old_node, 'active_failure', None),
            children=[convert_node(c) for c in old_node.children],
            meta={}
        )
        return new_node

    new_tree = NewRenderTree(
        roots=[convert_node(r) for r in tree.roots],
        phase=tree.phase_name,
        phase_name=tree.phase_name,
        phase_colour=tree.phase_colour,
        lambda_omega=tree.lambda_omega,
        budget_warnings=[],
        symbol_errors=[],
        active_failures=[]
    )

    # Render Python code
    code = renderer.render(new_tree, app_name=name.title().replace('_', '').replace('-', ''))

    # Write Python source
    out_dir.mkdir(parents=True, exist_ok=True)
    output_files = renderer.output_files(name)
    py_file = out_dir / output_files[0]
    py_file.write_text(code, encoding='utf-8')
    print(f"Generated Python source: {py_file}")

    # Step 2: Compile with PyInstaller
    dist_dir = out_dir / 'dist'
    build_dir = out_dir / 'build'
    spec_file = out_dir / f'{name}.spec'

    # Determine icon (use default if not specified)
    icon_arg = []
    if args.icon and Path(args.icon).exists():
        icon_arg = ['--icon', args.icon]

    # PyInstaller arguments
    pyinstaller_args = [
        str(py_file),
        '--name', args.name or name,
        '--distpath', str(dist_dir),
        '--workpath', str(build_dir),
        '--specpath', str(out_dir),
        '--noconfirm',
    ]

    # Windowed mode (no console) for GUI apps
    if not args.console:
        pyinstaller_args.append('--windowed')

    # One file or one directory
    if args.onefile:
        pyinstaller_args.append('--onefile')

    # Add icon if specified
    pyinstaller_args.extend(icon_arg)

    # Hidden imports for Qt
    if backend in ['pyqt5', 'python-qt']:
        pyinstaller_args.extend(['--hidden-import', 'PyQt5.sip'])
    elif backend == 'pyqt6':
        pyinstaller_args.extend(['--hidden-import', 'PyQt6.sip'])

    print(f"\nRunning PyInstaller...")
    print(f"  Args: {' '.join(pyinstaller_args)}")

    try:
        import PyInstaller.__main__
        PyInstaller.__main__.run(pyinstaller_args)
    except Exception as e:
        print(f"PyInstaller error: {e}")
        return 1

    # Find the output executable
    if args.onefile:
        exe_name = (args.name or name) + ('.exe' if sys.platform == 'win32' else '')
        exe_path = dist_dir / exe_name
    else:
        exe_name = (args.name or name) + ('.exe' if sys.platform == 'win32' else '')
        exe_path = dist_dir / (args.name or name) / exe_name

    if exe_path.exists():
        print(f"\n{'='*60}")
        print(f"Successfully compiled executable!")
        print(f"  Output: {exe_path}")
        print(f"  Size: {exe_path.stat().st_size / 1024 / 1024:.1f} MB")
        print(f"{'='*60}")
    else:
        print(f"\nCompilation completed. Check {dist_dir} for output.")

    return 0


def cmd_pdf(args):
    """Generate a formatted PDF from a markdown, text, or JSON file."""
    try:
        from core.scripts.pdf_generator import generate_pdf_from_file, create_pdf_generator_app
    except ImportError as e:
        print(f"Error importing PDF generator: {e}")
        print("Install PDF support with: pip install -e core[pdf]")
        print("For the GUI utility, use: pip install -e core[pdf-gui]")
        return 1

    if getattr(args, 'gui', False):
        try:
            app_cls = create_pdf_generator_app(
                initial_input=(getattr(args, 'input_path', None) or args.input),
                initial_output=args.output,
            )
        except RuntimeError as e:
            print(f"Error launching PDF GUI: {e}")
            return 1
        app_cls().run()
        return 0

    input_path = getattr(args, 'input_path', None) or args.input
    if not input_path:
        print("Error: input is required unless you use --gui")
        return 1

    if not os.path.exists(input_path):
        print(f"Error: {input_path} not found")
        return 1

    try:
        output = generate_pdf_from_file(input_path, args.output)
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return 1

    print(f"Generated PDF: {output}")
    return 0


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="GUILDS CLI - Command-line toolkit for GUILDS specifications",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  guilds new MyApp                              Create new specification
  guilds validate myapp.guilds                  Check for errors
  guilds build myapp.guilds                     Build HTML SPA (default)
  guilds build myapp.guilds --backend python-tk Build tkinter app
  guilds build myapp.guilds --backend pyqt5     Build PyQt5 app
  guilds build myapp.guilds --backend pyqt6     Build PyQt6 app
  guilds build myapp.guilds --backend pyside6   Build PySide6 app
  guilds build myapp.guilds --backend cpp-qt    Build C++ Qt app
  guilds build myapp.guilds --backend cpp-imgui Build C++ ImGui app
  guilds compile myapp.guilds --backend pyside6 Compile to executable
  guilds compile myapp.guilds --onefile         Single-file executable
  guilds serve myapp.guilds                     Start dev server
  guilds serve --builder                        Start visual builder
  guilds export myapp.guilds json               Export to JSON
  guilds export myapp.guilds statemachine       Export flow state machines
  guilds pdf notes.md                           Generate a PDF from a local file
  guilds pdf --gui --input notes.md --output out.pdf
                                                Launch the PDF GUI with preloaded paths
        """
    )

    subparsers = parser.add_subparsers(dest='command', help='Commands')

    # new
    p_new = subparsers.add_parser('new', help='Create new specification')
    p_new.add_argument('name', help='Name for the new spec')
    p_new.add_argument('--force', '-f', action='store_true', help='Overwrite existing')

    # validate
    p_val = subparsers.add_parser('validate', help='Validate specification')
    p_val.add_argument('spec', help='Path to .guilds file')

    # build
    p_build = subparsers.add_parser('build', help='Build GUI for specified backend')
    p_build.add_argument('spec', help='Path to .guilds file')
    p_build.add_argument('--output', '-o', help='Output directory path')
    p_build.add_argument('--backend', '-b', choices=AVAILABLE_BACKENDS, default='html',
                        help='Output backend (default: html)')

    # render
    p_render = subparsers.add_parser('render', help='Render static output for a phase')
    p_render.add_argument('spec', help='Path to .guilds file')
    p_render.add_argument('phase', choices=['idle', 'orient', 'execute', 'verify', 'integrate', 'recover'])
    p_render.add_argument('--backend', '-b', choices=AVAILABLE_BACKENDS, default='html',
                        help='Output backend (default: html)')

    # serve
    p_serve = subparsers.add_parser('serve', help='Start dev server')
    p_serve.add_argument('spec', nargs='?', help='Path to .guilds file')
    p_serve.add_argument('--builder', action='store_true', help='Serve the visual builder')
    p_serve.add_argument('--port', '-p', type=int, default=8080, help='Port number')

    # export
    p_export = subparsers.add_parser('export', help='Export to other formats')
    p_export.add_argument('spec', help='Path to .guilds file')
    p_export.add_argument('format', choices=['json', 'react', 'vue', 'events', 'statemachine'])

    # compile
    p_compile = subparsers.add_parser('compile', help='Compile to standalone executable')
    p_compile.add_argument('spec', help='Path to .guilds file')
    p_compile.add_argument('--output', '-o', help='Output directory path')
    p_compile.add_argument('--backend', '-b', choices=COMPILABLE_BACKENDS, default='pyside6',
                          help='Python Qt backend (default: pyside6)')
    p_compile.add_argument('--name', '-n', help='Executable name (default: spec name)')
    p_compile.add_argument('--onefile', '-F', action='store_true',
                          help='Create single-file executable')
    p_compile.add_argument('--console', '-c', action='store_true',
                          help='Show console window (default: windowed)')
    p_compile.add_argument('--icon', '-i', help='Path to icon file (.ico on Windows)')

    # pdf
    p_pdf = subparsers.add_parser('pdf', help='Generate a formatted PDF from a local file')
    p_pdf.add_argument('input', nargs='?', help='Path to input file (.md, .txt, .json)')
    p_pdf.add_argument('--input', dest='input_path', help='Optional input path alias (useful with --gui)')
    p_pdf.add_argument('--output', '-o', help='Output PDF path')
    p_pdf.add_argument('--gui', action='store_true', help='Launch the Kivy PDF generator GUI')

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 0

    commands = {
        'new': cmd_new,
        'validate': cmd_validate,
        'build': cmd_build,
        'render': cmd_render,
        'serve': cmd_serve,
        'export': cmd_export,
        'compile': cmd_compile,
        'pdf': cmd_pdf,
    }

    return commands[args.command](args)


if __name__ == '__main__':
    sys.exit(main())
